wallpaper {
    monitor = DP-3
    path = ~/.wallpapers/mtfuji.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.wallpapers/mtfuji.png
    fit_mode = cover
}

splash = false
