# === input ===
kb_layout = us
repeat_rate = 25
repeat_delay = 300

# === General ===
#background_color = 000000
general {
   gaps_in = 5
   gaps_out = 8
   border_size = 3

   col.active_border = 0xffE0BBE4
}

decoration {
   rounding = 12
}

font = JetbrainsMonoNL Nerd Font Mono:size=12


# === Display === 

monitor = DP-3, 1980x1080@144, 0x0, 1 
monitor = HDMI-A-1, 1920x1080@60, 1920x-420, 1, transform, 3 

# === Workspaces ===

#monitor 1
workspace = 1, monitor:DP-3, default:true, persistent:true 
workspace = 2, monitor:DP-3, persistent:true 
workspace = 3, monitor:DP-3, persistent:true 
workspace = 4, monitor:DP-3, persistent:true

#monitor 2
workspace = 5, monitor:HDMI-A-1, default:true, persistent:true
workspace = 6, monitor:HDMI-A-1, persistent:true
workspace = 7, monitor:HDMI-A-1, persistent:true
workspace = 8, monitor:HDMI-A-1, persistent:true


# === keyboard Shortcuts ===
bind = SUPER, Q, exec, kitty
bind = SUPER, C, killactive
bind = SUPER, M, exit 
bind = SUPER, R, exec, rofi -show drun
bind = SUPER, F, exec, firefox
bind = SUPER, L, exec, hyprlock
bind = SUPER, N, exec, obsidian

bind = SUPER, 1, workspace, 1
bind = SUPER, 1, workspace, 5
bind = SUPER, 1, focusmonitor, DP-3

bind = SUPER, 2, workspace, 2
bind = SUPER, 2, workspace, 6
bind = SUPER, 2, focusmonitor, DP-3

bind = SUPER, 3, workspace, 3
bind = SUPER, 3, workspace, 7
bind = SUPER, 3, focusmonitor, DP-3

bind = SUPER, 4, workspace, 4
bind = SUPER, 4, workspace, 8
bind = SUPER, 4, focusmonitor, DP-3

bind = SUPER, left, movewindow, mon:-1
bind = SUPER, right, movewindow, mon:+1 


# === Window Rules ===
windowrule = match:float true, center 1
windowrule = match:fullscreen true, rounding 0

# === Layer Rules ===
layerrule = ignore_alpha 0.5, match:namespace waybar
layerrule = blur off, match:namespace waybar
layerrule = blur_popups off, match:namespace waybar
layerrule = xray 1, match:namespace waybar
layerrule = dim_around off, match:namespace waybar

# === Misc ===
misc {
   force_default_wallpaper = 0
   disable_hyprland_logo = true
}

# === Widgets and Utils ===
execr-once = hyprpaper
execr-once = waybar
